### ISSUE TITLE
garbage

### ISSUE THREAD

**Issue by Fangoboyo** [darverdevs/DupePatch#1]
garbage doesnt even have pom xml cringe cringe bad haha idfk what im doing haha

**Comment by UnknownKeeper88888** [comment]
cum

**Comment by Fangoboyo** [comment]
i agree

**Comment by ColdDev** [comment]
shut up :sob: :sob: :sob: :sob:

**Comment by UnknownKeeper88888** [comment]
goody ahh ahh
